### ISSUE TITLE
No config file for 1.7.10

### ISSUE THREAD

**Issue by Shahelion** [MattCzyr/ConsoleFilter#2]
Simply, it doesn't generate one when the game is run with the mod.

**Comment by MattCzyr** [comment]
Can't reproduce this issue. I've tried in several scenarios and a config file was generated every time.

Try adding the file to your config folder yourself. [Here's a standard ConsoleFilter.cfg file.](https://www.dropbox.com/s/uzp1n7a4quk6i73/ConsoleFilter.cfg?dl=0)
