### ISSUE TITLE
Config wipes itself on server start, thus doesn't filter messages (1.12.2)

### ISSUE THREAD

**Issue by ControlCoreAngel** [MattCzyr/ConsoleFilter#7]
We recently picked up this mod to filter out Multicraft's "There are 0/84 players online:" message, but on working with the config, it appears to completely wipe strings from itself after the server is started (via stop/start and restart both). On startup, the mod displays in console: "0 message(s) to be filtered."
I'm specifically trying to filter the string "players online" (without the ", of course).

Am I inputting strings incorrectly, or is this just an odd error?

Here is our config when I attempt to put the string in:
![Screen Shot 2021-06-30 at 3 28 58 PM](https://user-images.githubusercontent.com/86745716/124027352-61072480-d9b8-11eb-870c-aaf948b138a1.png)

Here is how our config looks after the server is started:
![Screen Shot 2021-06-30 at 3 29 10 PM](https://user-images.githubusercontent.com/86745716/124027368-65334200-d9b8-11eb-8fa0-e379fcfbf9e9.png)

**Comment by MattCzyr** [comment]
The config field expects a list of strings, so you need to surround *players online* with quotes, like *"players online"*.

**Comment by ControlCoreAngel** [comment]
I may be stupid!
Thanks much.

**Comment by ControlCoreAngel** [comment]
@MattCzyr 
> The config field expects a list of strings, so you need to surround _players online_ with quotes, like _"players online"_.

So, I've put quotes around the string like you told me to, however, the config once again wiped itself after the server was started. It saved properly, it just seems to be deleting strings from itself when the server is started. In console, it still gives the "0 message(s) to filter" message.

This is my config file prior to server starting:
![Screen Shot 2021-06-30 at 8 22 50 PM](https://user-images.githubusercontent.com/86745716/124051110-78a6d300-d9e1-11eb-8f35-e8f71cb704f3.png)

Post-server start, it appears identical to the empty version of the config in my original post.

Let me know if I can give you any information at all that could help you. I don't know what's up, the mod gives me no errors.

EDIT: It also has appeared to have cloned a corrupted version of itself in our configs folder. It's not readable.
![Screen Shot 2021-06-30 at 8 29 34 PM](https://user-images.githubusercontent.com/86745716/124051423-1e5a4200-d9e2-11eb-9c25-3b7b65cfa738.png)
